#!/bin/sh

juju-log "MongoDB instance server departed. Starting local mongodb service..."
#!/bin/sh

app_name=`config-get app_name`
service $app_name status && service $app_name stop

host=`relation-get private-address`
install_root="/opt"
site_dir="$install_root/$app_name"
site_db_dir="$install_root/my-site-db"

restore_data() {
  juju-log "Restoring mongodb data locally from host..."
  cd ${site_db_dir}
  tar -xvzf my-site-db-host.tar.gz
  mongorestore
  rm -r dump
  cd -
}

if [ -z "$host" ] ; then
  service mongodb restart || service mongodb start
    
  juju-log "Configuring ${app_name} for local mongodb server..."
  config_file_path=$site_dir/config/config.js
  MY_DIR=`dirname $0`
  $MY_DIR/config-changed
  if [ -f $config_file_path ]; then
    juju-log "Writing $app_name config file $config_file_path"
    sed -i "s/mongo_host.*/mongo_host\" : \"localhost\"/" $config_file_path
    sed -i "s/mongo_port.*/mongo_port\" : 27017/" $config_file_path
  fi
  
  #if [ -f ${site_db_dir}/my-site-db-host.tar.gz ]; then
   # restore_data
  #fi
fi


service my-site restart
